module.exports = {
    ROOT_API:{
        HOME:"/",
        COURSES:'/courses',
        MEMBERS:'/student'
    },
    LOGIN:{
        SIGN_IN:"/sign-in",
        CREATE:"/create-users"
    },
    COURSES:{
        CREATE:'/create',
        get_members_by_courseID:'/course/:ID'
    },
    MEMBERS:{
        get_course_of_member:'/:ID',
        create_members:'/create'
    }
}